"""add_student_semester_fields

Revision ID: 0b2eb7c63375
Revises: d67dbc5e14b9
Create Date: 2026-02-12 08:08:35.113226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2eb7c63375'
down_revision: Union[str, None] = 'd67dbc5e14b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_semester_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_usn', sa.String(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_usn'], ['students.usn'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_semester_enrollments_student_usn'), 'student_semester_enrollments', ['student_usn'], unique=False)
    op.add_column('students', sa.Column('is_lateral_entry', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('students', sa.Column('current_semester', sa.Integer(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'current_semester')
    op.drop_column('students', 'is_lateral_entry')
    op.drop_index(op.f('ix_student_semester_enrollments_student_usn'), table_name='student_semester_enrollments')
    op.drop_table('student_semester_enrollments')
    # ### end Alembic commands ###
