"""Add notification preferences

Revision ID: 538e05fef224
Revises: 6586b2709c89
Create Date: 2026-02-08 10:52:16.329654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538e05fef224'
down_revision: Union[str, None] = '6586b2709c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('semester_no', sa.Integer(), nullable=False),
    sa.Column('semester_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_cohort_id'), 'semesters', ['cohort_id'], unique=False)
    op.drop_index('ix_audit_logs_table_created', table_name='audit_logs')
    op.drop_index('ix_backlog_cohort_result', table_name='backlog_attempts')
    op.drop_index('ix_backlog_offering_id', table_name='backlog_attempts')
    op.drop_index('ix_backlog_student_usn', table_name='backlog_attempts')
    op.drop_index('ix_co_subject', table_name='course_outcomes')
    op.drop_index('ix_exams_offering_type', table_name='exams')
    op.drop_index('ix_exams_status_cohort', table_name='exams')
    op.drop_index('ix_finalmarks_cohort_usn', table_name='final_marks')
    op.add_column('profiles', sa.Column('notification_preferences', sa.String(), nullable=True))
    op.drop_index('ix_questions_section_seq', table_name='questions')
    op.drop_index('ix_semester_results_usn_sem', table_name='semester_results')
    op.drop_index('ix_student_marks_exam_student', table_name='student_marks')
    op.drop_index('ix_sqm_exam_usn', table_name='student_question_marks')
    op.drop_index('ix_students_cohort_status', table_name='students')
    op.drop_index('ix_subquestions_question', table_name='sub_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subquestions_question', 'sub_questions', ['question_id'], unique=False)
    op.create_index('ix_students_cohort_status', 'students', ['cohort_id', 'status'], unique=False)
    op.create_index('ix_sqm_exam_usn', 'student_question_marks', ['exam_id', 'usn'], unique=False)
    op.create_index('ix_student_marks_exam_student', 'student_marks', ['exam_id', 'student_id'], unique=False)
    op.create_index('ix_semester_results_usn_sem', 'semester_results', ['usn', 'semester'], unique=False)
    op.create_index('ix_questions_section_seq', 'questions', ['section_id', 'sequence'], unique=False)
    op.drop_column('profiles', 'notification_preferences')
    op.create_index('ix_finalmarks_cohort_usn', 'final_marks', ['cohort_id', 'usn'], unique=False)
    op.create_index('ix_exams_status_cohort', 'exams', ['status', 'cohort_id'], unique=False)
    op.create_index('ix_exams_offering_type', 'exams', ['offering_id', 'exam_type'], unique=False)
    op.create_index('ix_co_subject', 'course_outcomes', ['subject_id'], unique=False)
    op.create_index('ix_backlog_student_usn', 'backlog_attempts', ['student_usn'], unique=False)
    op.create_index('ix_backlog_offering_id', 'backlog_attempts', ['offering_id'], unique=False)
    op.create_index('ix_backlog_cohort_result', 'backlog_attempts', ['semester_attempted', 'result'], unique=False)
    op.create_index('ix_audit_logs_table_created', 'audit_logs', ['table_name', 'created_at'], unique=False)
    op.drop_index(op.f('ix_semesters_cohort_id'), table_name='semesters')
    op.drop_table('semesters')
    # ### end Alembic commands ###
