"""fix_audit_gradescale_schema

Revision ID: 6586b2709c89
Revises: 004_production_indexes
Create Date: 2026-02-07 17:07:56.198438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6586b2709c89'
down_revision: Union[str, None] = '004_production_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually to keep indexes ###
    op.create_table('grade_scales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('program_specific_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('pso_code', sa.String(), nullable=False),
    sa.Column('pso_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_pso_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('co_id', sa.UUID(), nullable=False),
    sa.Column('pso_id', sa.UUID(), nullable=False),
    sa.Column('correlation_level', sa.Integer(), nullable=False),
    sa.Column('version_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ),
    sa.ForeignKeyConstraint(['pso_id'], ['program_specific_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.String(), nullable=True))
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # op.drop_index('ix_audit_logs_table_created', table_name='audit_logs') # KEEP THIS
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    # op.drop_index('ix_backlog_cohort_result', table_name='backlog_attempts') # KEEP THIS
    # op.drop_index('ix_backlog_offering_id', table_name='backlog_attempts') # KEEP THIS
    # op.drop_index('ix_backlog_student_usn', table_name='backlog_attempts') # KEEP THIS
    op.create_index(op.f('ix_backlog_attempts_offering_id'), 'backlog_attempts', ['offering_id'], unique=False)
    op.create_index(op.f('ix_backlog_attempts_student_usn'), 'backlog_attempts', ['student_usn'], unique=False)
    # op.drop_index('ix_co_subject', table_name='course_outcomes') # KEEP THIS
    # op.drop_index('ix_exams_offering_type', table_name='exams') # KEEP THIS
    # op.drop_index('ix_exams_status_cohort', table_name='exams') # KEEP THIS
    # op.drop_index('ix_finalmarks_cohort_usn', table_name='final_marks') # KEEP THIS
    op.add_column('grading_rules', sa.Column('grade_scale_id', sa.UUID(), nullable=False))
    op.add_column('grading_rules', sa.Column('description', sa.String(length=100), nullable=True))
    op.create_index('ix_grading_rule_range', 'grading_rules', ['grade_scale_id', 'min_percentage', 'max_percentage'], unique=False)
    op.create_index(op.f('ix_grading_rules_grade_scale_id'), 'grading_rules', ['grade_scale_id'], unique=False)
    op.create_unique_constraint('uq_grading_rule_grade', 'grading_rules', ['grade_scale_id', 'grade'])
    op.create_foreign_key(None, 'grading_rules', 'grade_scales', ['grade_scale_id'], ['id'], ondelete='CASCADE')
    # op.drop_index('ix_questions_section_seq', table_name='questions') # KEEP THIS
    op.create_index(op.f('ix_regulations_college_id'), 'regulations', ['college_id'], unique=False)
    op.create_foreign_key(None, 'regulations', 'grade_scales', ['grade_scale_id'], ['id'])
    op.alter_column('semester_promotions', 'total_students',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('semester_promotions', 'students_promoted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('semester_promotions', 'students_detained',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('semester_promotions', 'students_on_hold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_semester_promotions_cohort_id'), 'semester_promotions', ['cohort_id'], unique=False)
    # op.drop_index('ix_semester_results_usn_sem', table_name='semester_results') # KEEP THIS
    # op.drop_index('ix_student_marks_exam_student', table_name='student_marks') # KEEP THIS
    # op.drop_index('ix_sqm_exam_usn', table_name='student_question_marks') # KEEP THIS
    op.create_index(op.f('ix_student_semester_status_promotion_id'), 'student_semester_status', ['promotion_id'], unique=False)
    op.create_index(op.f('ix_student_semester_status_student_usn'), 'student_semester_status', ['student_usn'], unique=False)
    # op.drop_index('ix_students_cohort_status', table_name='students') # KEEP THIS
    # op.drop_index('ix_subquestions_question', table_name='sub_questions') # KEEP THIS
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_subquestions_question', 'sub_questions', ['question_id'], unique=False)
    # op.create_index('ix_students_cohort_status', 'students', ['cohort_id', 'status'], unique=False)
    op.drop_index(op.f('ix_student_semester_status_student_usn'), table_name='student_semester_status')
    op.drop_index(op.f('ix_student_semester_status_promotion_id'), table_name='student_semester_status')
    # op.create_index('ix_sqm_exam_usn', 'student_question_marks', ['exam_id', 'usn'], unique=False)
    # op.create_index('ix_student_marks_exam_student', 'student_marks', ['exam_id', 'student_id'], unique=False)
    # op.create_index('ix_semester_results_usn_sem', 'semester_results', ['usn', 'semester'], unique=False)
    op.drop_index(op.f('ix_semester_promotions_cohort_id'), table_name='semester_promotions')
    op.alter_column('semester_promotions', 'students_on_hold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('semester_promotions', 'students_detained',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('semester_promotions', 'students_promoted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('semester_promotions', 'total_students',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('regulations_grade_scale_id_fkey', 'regulations', type_='foreignkey')
    op.drop_index(op.f('ix_regulations_college_id'), table_name='regulations')
    # op.create_index('ix_questions_section_seq', 'questions', ['section_id', 'sequence'], unique=False)
    op.drop_constraint('grading_rules_grade_scale_id_fkey', 'grading_rules', type_='foreignkey')
    op.drop_constraint('uq_grading_rule_grade', 'grading_rules', type_='unique')
    op.drop_index(op.f('ix_grading_rules_grade_scale_id'), table_name='grading_rules')
    op.drop_index('ix_grading_rule_range', table_name='grading_rules')
    op.drop_column('grading_rules', 'description')
    op.drop_column('grading_rules', 'grade_scale_id')
    # op.create_index('ix_finalmarks_cohort_usn', 'final_marks', ['cohort_id', 'usn'], unique=False)
    # op.create_index('ix_exams_status_cohort', 'exams', ['status', 'cohort_id'], unique=False)
    # op.create_index('ix_exams_offering_type', 'exams', ['offering_id', 'exam_type'], unique=False)
    # op.create_index('ix_co_subject', 'course_outcomes', ['subject_id'], unique=False)
    op.drop_index(op.f('ix_backlog_attempts_student_usn'), table_name='backlog_attempts')
    op.drop_index(op.f('ix_backlog_attempts_offering_id'), table_name='backlog_attempts')
    # op.create_index('ix_backlog_student_usn', 'backlog_attempts', ['student_usn'], unique=False)
    # op.create_index('ix_backlog_offering_id', 'backlog_attempts', ['offering_id'], unique=False)
    # op.create_index('ix_backlog_cohort_result', 'backlog_attempts', ['semester_attempted', 'result'], unique=False)
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    # op.create_index('ix_audit_logs_table_created', 'audit_logs', ['table_name', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_table('co_pso_mappings')
    op.drop_table('program_specific_outcomes')
    op.drop_table('grade_scales')
    # ### end Alembic commands ###
