"""Add Remedial Actions Corrected

Revision ID: d67dbc5e14b9
Revises: ddbd7f6dc4a8
Create Date: 2026-02-11 15:12:18.738225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67dbc5e14b9'
down_revision: Union[str, None] = 'ddbd7f6dc4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remedial_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('ASSIGNMENT', 'EXTRA_CLASS', 'COUNSELING', 'RETEST', 'OTHER', name='remedialactiontype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', name='remedialactionstatus'), nullable=False),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['profiles.user_id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remedial_actions_offering_id'), 'remedial_actions', ['offering_id'], unique=False)
    op.create_index(op.f('ix_remedial_actions_student_id'), 'remedial_actions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remedial_actions_student_id'), table_name='remedial_actions')
    op.drop_index(op.f('ix_remedial_actions_offering_id'), table_name='remedial_actions')
    op.drop_table('remedial_actions')
    # ### end Alembic commands ###
