"""initial_schema

Revision ID: ef9599cb5b7c
Revises: 
Create Date: 2026-02-07 11:55:05.758649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9599cb5b7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bloom_taxonomy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', 'level_name', name='uq_bloom_version_level')
    )
    op.create_table('colleges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('grading_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('min_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grade_point', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('hod_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('PRINCIPAL', 'HOD', 'TEACHER', 'STUDENT', name='app_role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('duration_semesters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cohorts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('po_code', sa.String(), nullable=False),
    sa.Column('po_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('usn', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_index(op.f('ix_student_enrollments_student_id'), 'student_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_usn'), 'student_enrollments', ['usn'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('curriculum_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('admission_semester', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('usn')
    )
    op.create_table('subject_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('semester_no', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.Column('regulation_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'cohort_id', 'semester_no', name='uq_subject_cohort_semester')
    )
    op.create_table('activity_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'usn', name='uq_activity_offering_usn')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('assignment_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('due_before_exam', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'usn', name='uq_attendance_offering_usn')
    )
    op.create_table('course_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('co_code', sa.String(), nullable=False),
    sa.Column('co_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bloom_id', sa.UUID(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(subject_id IS NOT NULL AND offering_id IS NULL) OR (subject_id IS NULL AND offering_id IS NOT NULL)', name='ck_course_outcomes_single_parent'),
    sa.ForeignKeyConstraint(['bloom_id'], ['bloom_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_teacher_id'), 'exams', ['teacher_id'], unique=False)
    op.create_table('final_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usn', sa.String(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('internal_1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('internal_2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assignment_1', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('assignment_2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('attendance', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('activity', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('external_marks', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('is_backlog', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_marks_student_id'), 'final_marks', ['student_id'], unique=False)
    op.create_index(op.f('ix_final_marks_usn'), 'final_marks', ['usn'], unique=False)
    op.create_table('semester_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usn', sa.String(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('earned_credits', sa.Integer(), nullable=True),
    sa.Column('sgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_results_student_id'), 'semester_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_semester_results_usn'), 'semester_results', ['usn'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('unit_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('entered_by', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_po_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('co_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('correlation_level', sa.Integer(), nullable=False),
    sa.Column('version_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('required_questions', sa.Integer(), nullable=False),
    sa.Column('selection_mode', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('marks_per_question', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("selection_mode IN ('ALL', 'BEST_N', 'FIRST_N')", name='ck_exam_sections_selection_mode'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('co_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('bloom_id', sa.UUID(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bloom_id'], ['bloom_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('co_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('bloom_id', sa.UUID(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bloom_id'], ['bloom_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('sub_question_id', sa.UUID(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('entered_by', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['sub_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_marks_student_id'), 'student_marks', ['student_id'], unique=False)
    op.create_table('student_question_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('sub_question_id', sa.UUID(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('entered_by', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['sub_questions.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_question_marks_usn'), 'student_question_marks', ['usn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_question_marks_usn'), table_name='student_question_marks')
    op.drop_table('student_question_marks')
    op.drop_index(op.f('ix_student_marks_student_id'), table_name='student_marks')
    op.drop_table('student_marks')
    op.drop_table('sub_questions')
    op.drop_table('questions')
    op.drop_table('topics')
    op.drop_table('exam_snapshots')
    op.drop_table('exam_sections')
    op.drop_table('co_po_mappings')
    op.drop_table('assignment_marks')
    op.drop_table('units')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_semester_results_usn'), table_name='semester_results')
    op.drop_index(op.f('ix_semester_results_student_id'), table_name='semester_results')
    op.drop_table('semester_results')
    op.drop_index(op.f('ix_final_marks_usn'), table_name='final_marks')
    op.drop_index(op.f('ix_final_marks_student_id'), table_name='final_marks')
    op.drop_table('final_marks')
    op.drop_index(op.f('ix_exams_teacher_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_table('course_outcomes')
    op.drop_table('attendance_marks')
    op.drop_table('assignments')
    op.drop_table('activity_marks')
    op.drop_table('subject_offerings')
    op.drop_table('students')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_student_enrollments_usn'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_student_id'), table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_table('sections')
    op.drop_table('program_outcomes')
    op.drop_table('curriculum_versions')
    op.drop_table('cohorts')
    op.drop_table('programs')
    op.drop_table('user_roles')
    op.drop_table('departments')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('grading_rules')
    op.drop_table('colleges')
    op.drop_table('bloom_taxonomy')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
