"""Add system_settings table

Revision ID: ffc6e82e9eed
Revises: 0b2eb7c63375
Create Date: 2026-02-12 14:32:42.556187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc6e82e9eed'
down_revision: Union[str, None] = '0b2eb7c63375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_exams_cohort_id'), 'exams', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_exams_exam_type'), 'exams', ['exam_type'], unique=False)
    op.create_index(op.f('ix_exams_offering_id'), 'exams', ['offering_id'], unique=False)
    op.create_index(op.f('ix_exams_status'), 'exams', ['status'], unique=False)
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_index(op.f('ix_final_marks_cohort_id'), 'final_marks', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_final_marks_offering_id'), 'final_marks', ['offering_id'], unique=False)
    op.create_index(op.f('ix_final_marks_subject_id'), 'final_marks', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_question_marks_exam_id'), 'student_question_marks', ['exam_id'], unique=False)
    op.create_index(op.f('ix_student_question_marks_sub_question_id'), 'student_question_marks', ['sub_question_id'], unique=False)
    op.create_index(op.f('ix_students_admission_semester'), 'students', ['admission_semester'], unique=False)
    op.create_index(op.f('ix_students_cohort_id'), 'students', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_students_current_semester'), 'students', ['current_semester'], unique=False)
    op.create_index(op.f('ix_students_section_id'), 'students', ['section_id'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_section_id'), table_name='students')
    op.drop_index(op.f('ix_students_current_semester'), table_name='students')
    op.drop_index(op.f('ix_students_cohort_id'), table_name='students')
    op.drop_index(op.f('ix_students_admission_semester'), table_name='students')
    op.drop_index(op.f('ix_student_question_marks_sub_question_id'), table_name='student_question_marks')
    op.drop_index(op.f('ix_student_question_marks_exam_id'), table_name='student_question_marks')
    op.drop_index(op.f('ix_final_marks_subject_id'), table_name='final_marks')
    op.drop_index(op.f('ix_final_marks_offering_id'), table_name='final_marks')
    op.drop_index(op.f('ix_final_marks_cohort_id'), table_name='final_marks')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_status'), table_name='exams')
    op.drop_index(op.f('ix_exams_offering_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_type'), table_name='exams')
    op.drop_index(op.f('ix_exams_cohort_id'), table_name='exams')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
